project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: Nathan Wu
  twitter-card:
   creator: "@NathanJWu"
  site-url: https://nathanw23.github.io
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Research
        menu:
        - text: Papers
          href: papers.qmd
        - text: Posters
          href: posters.qmd
      - href: posts.qmd
        text: Blog
      - href: resources.qmd
        text: Resources

    right: 
      - icon: github
        href: https://github.com/nathanw23
      - icon: twitter
        href: https://twitter.com/NathanJWu
  page-footer:
    left: "This website is built with ❤️ and [Quarto](https://quarto.org/)"
    right: "© 2026 Nathan Wu"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full
