---
title: "GelGenie: an AI-powered framework for gel electrophoresis image analysis"
type: "article"
author: "Matthew Aquilina, Nathan Wu, Kiros Kwan, Filip Busic, James Dodd, Laura Nicolas-Sanez, Alan O'Callaghan, Peter Bankhead, Katherine Dunn"
year: "2025"
publication: "Nature Communications"
preprint: ""
doi: "https://doi.org/10.1038/s41467-025-59189-0"
materials: ""
toc: false
categories:
  - journal article
---

## Abstract

Gel electrophoresis is a ubiquitous laboratory method for the separation and semi-quantitative analysis of biomolecules. However, gel image analysis principles have barely advanced for decades, in stark contrast to other fields where AI has revolutionised data processing. Here, we show that an AI-based system can automatically identify gel bands in seconds for a wide range of experimental conditions, surpassing the capabilities of current software in both ease-of-use and versatility. We use a dataset containing 500+ images of manually-labelled gels to train various U-Nets to accurately identify bands through segmentation, i.e. classifying pixels as ‘band’ or ‘background’. When applied to gel electrophoresis data from other laboratories, our system generates results that quantitatively match those of the original authors. We have publicly released our models through GelGenie, an open-source application that allows users to extract bands from gel images on their own devices, with no expert knowledge or experience required.