---
title: "The application of nanotechnology for quantification of circulating tumour DNA in liquid biopsies: a systematic review"
type: "article"
author: "Nathan Wu, Matthew Aquilina, Bin-Zhi Qian, Remco Loos, Ines Gonzalez-Garcia, Cristina Costa Santini, Katherine Dunn"
year: "03/18/2022"
publication: "IEEE Reviews in Biomedical Engineering"
preprint: ""
doi: "https://doi.org/10.1109/RBME.2022.3159389"
materials: ""
toc: false
categories:
  - journal article
  - systematic review
  - ctDNA
  - nanotechnology
---

## Abstract

Technologies for quantifying circulating tumour DNA (ctDNA) in liquid biopsies could enable real-time measurements of cancer progression, profoundly impacting patient care. Sequencing methods can be too complex and time-consuming for regular point-of-care monitoring, but nanotechnology offers an alternative, harnessing the unique properties of objects tens to hundreds of nanometres in size. This systematic review was performed to identify all examples of nanotechnology-based ctDNA detection and assess their potential for clinical use. Google Scholar, PubMed, Web of Science, Google Patents, Espacenet and Embase/MEDLINE were searched up to 23rd March 2021. The review identified nanotechnology-based methods for ctDNA detection for which quantitative measures (e.g., limit of detection, LOD) were reported and biologically relevant samples were used. The pre-defined inclusion criteria were met by 66 records. LODs ranged from 10 zM to 50nM. 25 records presented an LOD of 10fM or below. Nanotechnology-based approaches could provide the basis for the next wave of advances in ctDNA diagnostics, enabling analysis at the point-of-care, but none are currently used clinically. Further work is needed in development and validation; trade-offs are expected between different performance measures e.g., number of sequences detected and time to result.